const bleitem1 = document.createElement('div');
        bleitem1.classList.add('bleItem');
        bleitem1.classList.add('bleItemhover');
        bleitem1.innerHTML = 'FR_BLE_0001';
        content.appendChild(bleitem1);
        const bleitem2 = document.createElement('div');
        bleitem2.classList.add('bleItem');
        bleitem2.classList.add('bleItemhover');
        bleitem2.innerHTML = 'FR_BLE_0002';
        content.appendChild(bleitem2);
        const bleitem3 = document.createElement('div');
        bleitem3.classList.add('bleItem');
        bleitem3.classList.add('bleItemhover');
        bleitem3.innerHTML = 'FR_BLE_0003';
        content.appendChild(bleitem3);
        const bleitem4 = document.createElement('div');
        bleitem4.classList.add('bleItem');
        bleitem4.classList.add('bleItemhover');
        bleitem4.innerHTML = 'FR_BLE_0004';
        content.appendChild(bleitem4);
        const bleitem5 = document.createElement('div');
        bleitem5.classList.add('bleItem');
        bleitem5.classList.add('bleItemhover');
        bleitem5.innerHTML = 'FR_BLE_0005';
        content.appendChild(bleitem5);
        const bleitem6 = document.createElement('div');
        bleitem6.classList.add('bleItem');
        bleitem6.classList.add('bleItemhover');
        bleitem6.innerHTML = 'FR_BLE_0006';
        content.appendChild(bleitem6);
        const bleitem7 = document.createElement('div');
        bleitem7.classList.add('bleItem');
        bleitem7.classList.add('bleItemhover');
        bleitem7.innerHTML = 'FR_BLE_0007';
        content.appendChild(bleitem7);
        const bleitem8 = document.createElement('div');
        bleitem8.classList.add('bleItem');
        bleitem8.classList.add('bleItemhover');
        bleitem8.innerHTML = 'FR_BLE_0008';
        content.appendChild(bleitem8);
        const bleitem9 = document.createElement('div');
        bleitem9.classList.add('bleItem');
        bleitem9.classList.add('bleItemhover');
        bleitem9.innerHTML = 'FR_BLE_0009';
        content.appendChild(bleitem1);
        const bleitem10 = document.createElement('div');
        bleitem10.classList.add('bleItem');
        bleitem10.classList.add('bleItemhover');
        bleitem10.innerHTML = 'FR_BLE_0010';
        content.appendChild(bleitem10);
        const bleitem11 = document.createElement('div');
        bleitem11.classList.add('bleItem');
        bleitem11.classList.add('bleItemhover');
        bleitem11.innerHTML = 'FR_BLE_0011';
        content.appendChild(bleitem11);
        const bleitem12 = document.createElement('div');
        bleitem12.classList.add('bleItem');
        bleitem12.classList.add('bleItemhover');
        bleitem12.innerHTML = 'FR_BLE_0012';
        content.appendChild(bleitem12);
        const bleitem13 = document.createElement('div');
        bleitem13.classList.add('bleItem');
        bleitem13.classList.add('bleItemhover');
        bleitem13.innerHTML = 'FR_BLE_0013';
        content.appendChild(bleitem13);
        const bleitem14 = document.createElement('div');
        bleitem14.classList.add('bleItem');
        bleitem14.classList.add('bleItemhover');
        bleitem14.innerHTML = 'FR_BLE_0014';
        content.appendChild(bleitem14);
        const bleitem15 = document.createElement('div');
        bleitem15.classList.add('bleItem');
        bleitem15.classList.add('bleItemhover');
        bleitem15.innerHTML = 'FR_BLE_0015';
        content.appendChild(bleitem15);
        const bleitem16 = document.createElement('div');
        bleitem16.classList.add('bleItem');
        bleitem16.classList.add('bleItemhover');
        bleitem16.innerHTML = 'FR_BLE_0016';
        content.appendChild(bleitem16);
        const bleitem17 = document.createElement('div');
        bleitem17.classList.add('bleItem');
        bleitem17.classList.add('bleItemhover');
        bleitem17.innerHTML = 'FR_BLE_0017';
        content.appendChild(bleitem17);
        const bleitem18 = document.createElement('div');
        bleitem18.classList.add('bleItem');
        bleitem18.classList.add('bleItemhover');
        bleitem18.innerHTML = 'FR_BLE_0018';
        content.appendChild(bleitem18);
        const bleitem19 = document.createElement('div');
        bleitem19.classList.add('bleItem');
        bleitem19.classList.add('bleItemhover');
        bleitem19.innerHTML = 'FR_BLE_0019';
        content.appendChild(bleitem19);
        const bleitem20= document.createElement('div');
        bleitem20.classList.add('bleItem');
        bleitem20.classList.add('bleItemhover');
        bleitem20.innerHTML = 'FR_BLE_0020';
        content.appendChild(bleitem18);